repos:
  - repo: https://github.com/realm/SwiftLint
    rev: 0.59.1
    hooks:
      - id: swiftlint
        name: swiftlint-fix
        entry: bash -c 'export PATH="/opt/homebrew/bin:$PATH"; swiftlint --fix'
        language: system
        types: [swift]
      - id: swiftlint
        name: swiftlint-check
        entry: bash -c 'export PATH="/opt/homebrew/bin:$PATH"; swiftlint'
        language: system
        types: [swift]

  - repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.56.4
    hooks:
      - id: swiftformat
        name: swiftformat-with-version
        entry: bash -c 'export PATH="/opt/homebrew/bin:$PATH"; swiftformat --swiftversion 6.1.1 --config .swiftformat'
        language: system
        types: [swift]
