//
//  CountryData.swift
//  Tourism Beats
//
//  Created by Ariel Tyson on 20/9/24.
//

import Foundation

struct CountryData {
    static let allCountries: [CountryModel] = [
        CountryModel(name: "Afghanistan", code: "AF", flag: "🇦🇫"),
        CountryModel(name: "Albania", code: "AL", flag: "🇦🇱"),
        CountryModel(name: "Algeria", code: "DZ", flag: "🇩🇿"),
        CountryModel(name: "Andorra", code: "AD", flag: "🇦🇩"),
        CountryModel(name: "Angola", code: "AO", flag: "🇦🇴"),
        CountryModel(name: "Antigua and Barbuda", code: "AG", flag: "🇦🇬"),
        CountryModel(name: "Argentina", code: "AR", flag: "🇦🇷"),
        CountryModel(name: "Armenia", code: "AM", flag: "🇦🇲"),
        CountryModel(name: "Australia", code: "AU", flag: "🇦🇺"),
        CountryModel(name: "Austria", code: "AT", flag: "🇦🇹"),
        CountryModel(name: "Azerbaijan", code: "AZ", flag: "🇦🇿"),
        CountryModel(name: "Bahamas", code: "BS", flag: "🇧🇸"),
        CountryModel(name: "Bahrain", code: "BH", flag: "🇧🇭"),
        CountryModel(name: "Bangladesh", code: "BD", flag: "🇧🇩"),
        CountryModel(name: "Barbados", code: "BB", flag: "🇧🇧"),
        CountryModel(name: "Belarus", code: "BY", flag: "🇧🇾"),
        CountryModel(name: "Belgium", code: "BE", flag: "🇧🇪"),
        CountryModel(name: "Belize", code: "BZ", flag: "🇧🇿"),
        CountryModel(name: "Benin", code: "BJ", flag: "🇧🇯"),
        CountryModel(name: "Bhutan", code: "BT", flag: "🇧🇹"),
        CountryModel(name: "Bolivia", code: "BO", flag: "🇧🇴"),
        CountryModel(name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦"),
        CountryModel(name: "Botswana", code: "BW", flag: "🇧🇼"),
        CountryModel(name: "Brazil", code: "BR", flag: "🇧🇷"),
        CountryModel(name: "Brunei", code: "BN", flag: "🇧🇳"),
        CountryModel(name: "Bulgaria", code: "BG", flag: "🇧🇬"),
        CountryModel(name: "Burkina Faso", code: "BF", flag: "🇧🇫"),
        CountryModel(name: "Burundi", code: "BI", flag: "🇧🇮"),
        CountryModel(name: "Cabo Verde", code: "CV", flag: "🇨🇻"),
        CountryModel(name: "Cambodia", code: "KH", flag: "🇰🇭"),
        CountryModel(name: "Cameroon", code: "CM", flag: "🇨🇲"),
        CountryModel(name: "Canada", code: "CA", flag: "🇨🇦"),
        CountryModel(name: "Central African Republic", code: "CF", flag: "🇨🇫"),
        CountryModel(name: "Chad", code: "TD", flag: "🇹🇩"),
        CountryModel(name: "Chile", code: "CL", flag: "🇨🇱"),
        CountryModel(name: "China", code: "CN", flag: "🇨🇳"),
        CountryModel(name: "Colombia", code: "CO", flag: "🇨🇴"),
        CountryModel(name: "Comoros", code: "KM", flag: "🇰🇲"),
        CountryModel(name: "Congo (Congo-Brazzaville)", code: "CG", flag: "🇨🇬"),
        CountryModel(name: "Costa Rica", code: "CR", flag: "🇨🇷"),
        CountryModel(name: "Croatia", code: "HR", flag: "🇭🇷"),
        CountryModel(name: "Cuba", code: "CU", flag: "🇨🇺"),
        CountryModel(name: "Cyprus", code: "CY", flag: "🇨🇾"),
        CountryModel(name: "Czechia (Czech Republic)", code: "CZ", flag: "🇨🇿"),
        CountryModel(name: "Democratic Republic of the Congo", code: "CD", flag: "🇨🇩"),
        CountryModel(name: "Denmark", code: "DK", flag: "🇩🇰"),
        CountryModel(name: "Djibouti", code: "DJ", flag: "🇩🇯"),
        CountryModel(name: "Dominica", code: "DM", flag: "🇩🇲"),
        CountryModel(name: "Dominican Republic", code: "DO", flag: "🇩🇴"),
        CountryModel(name: "Ecuador", code: "EC", flag: "🇪🇨"),
        CountryModel(name: "Egypt", code: "EG", flag: "🇪🇬"),
        CountryModel(name: "El Salvador", code: "SV", flag: "🇸🇻"),
        CountryModel(name: "Equatorial Guinea", code: "GQ", flag: "🇬🇶"),
        CountryModel(name: "Eritrea", code: "ER", flag: "🇪🇷"),
        CountryModel(name: "Estonia", code: "EE", flag: "🇪🇪"),
        CountryModel(name: "Eswatini (Swaziland)", code: "SZ", flag: "🇸🇿"),
        CountryModel(name: "Ethiopia", code: "ET", flag: "🇪🇹"),
        CountryModel(name: "Fiji", code: "FJ", flag: "🇫🇯"),
        CountryModel(name: "Finland", code: "FI", flag: "🇫🇮"),
        CountryModel(name: "France", code: "FR", flag: "🇫🇷"),
        CountryModel(name: "Gabon", code: "GA", flag: "🇬🇦"),
        CountryModel(name: "Gambia", code: "GM", flag: "🇬🇲"),
        CountryModel(name: "Georgia", code: "GE", flag: "🇬🇪"),
        CountryModel(name: "Germany", code: "DE", flag: "🇩🇪"),
        CountryModel(name: "Ghana", code: "GH", flag: "🇬🇭"),
        CountryModel(name: "Greece", code: "GR", flag: "🇬🇷"),
        CountryModel(name: "Grenada", code: "GD", flag: "🇬🇩"),
        CountryModel(name: "Guatemala", code: "GT", flag: "🇬🇹"),
        CountryModel(name: "Guinea", code: "GN", flag: "🇬🇳"),
        CountryModel(name: "Guinea-Bissau", code: "GW", flag: "🇬🇼"),
        CountryModel(name: "Guyana", code: "GY", flag: "🇬🇾"),
        CountryModel(name: "Haiti", code: "HT", flag: "🇭🇹"),
        CountryModel(name: "Holy See", code: "VA", flag: "🇻🇦"),
        CountryModel(name: "Honduras", code: "HN", flag: "🇭🇳"),
        CountryModel(name: "Hungary", code: "HU", flag: "🇭🇺"),
        CountryModel(name: "Iceland", code: "IS", flag: "🇮🇸"),
        CountryModel(name: "India", code: "IN", flag: "🇮🇳"),
        CountryModel(name: "Indonesia", code: "ID", flag: "🇮🇩"),
        CountryModel(name: "Iran", code: "IR", flag: "🇮🇷"),
        CountryModel(name: "Iraq", code: "IQ", flag: "🇮🇶"),
        CountryModel(name: "Ireland", code: "IE", flag: "🇮🇪"),
        CountryModel(name: "Israel", code: "IL", flag: "🇮🇱"),
        CountryModel(name: "Italy", code: "IT", flag: "🇮🇹"),
        CountryModel(name: "Jamaica", code: "JM", flag: "🇯🇲"),
        CountryModel(name: "Japan", code: "JP", flag: "🇯🇵"),
        CountryModel(name: "Jordan", code: "JO", flag: "🇯🇴"),
        CountryModel(name: "Kazakhstan", code: "KZ", flag: "🇰🇿"),
        CountryModel(name: "Kenya", code: "KE", flag: "🇰🇪"),
        CountryModel(name: "Kiribati", code: "KI", flag: "🇰🇮"),
        CountryModel(name: "Kuwait", code: "KW", flag: "🇰🇼"),
        CountryModel(name: "Kyrgyzstan", code: "KG", flag: "🇰🇬"),
        CountryModel(name: "Laos", code: "LA", flag: "🇱🇦"),
        CountryModel(name: "Latvia", code: "LV", flag: "🇱🇻"),
        CountryModel(name: "Lebanon", code: "LB", flag: "🇱🇧"),
        CountryModel(name: "Lesotho", code: "LS", flag: "🇱🇸"),
        CountryModel(name: "Liberia", code: "LR", flag: "🇱🇷"),
        CountryModel(name: "Libya", code: "LY", flag: "🇱🇾"),
        CountryModel(name: "Liechtenstein", code: "LI", flag: "🇱🇮"),
        CountryModel(name: "Lithuania", code: "LT", flag: "🇱🇹"),
        CountryModel(name: "Luxembourg", code: "LU", flag: "🇱🇺"),
        CountryModel(name: "Madagascar", code: "MG", flag: "🇲🇬"),
        CountryModel(name: "Malawi", code: "MW", flag: "🇲🇼"),
        CountryModel(name: "Malaysia", code: "MY", flag: "🇲🇾"),
        CountryModel(name: "Maldives", code: "MV", flag: "🇲🇻"),
        CountryModel(name: "Mali", code: "ML", flag: "🇲🇱"),
        CountryModel(name: "Malta", code: "MT", flag: "🇲🇹"),
        CountryModel(name: "Marshall Islands", code: "MH", flag: "🇲🇭"),
        CountryModel(name: "Mauritania", code: "MR", flag: "🇲🇷"),
        CountryModel(name: "Mauritius", code: "MU", flag: "🇲🇺"),
        CountryModel(name: "Mexico", code: "MX", flag: "🇲🇽"),
        CountryModel(name: "Micronesia", code: "FM", flag: "🇫🇲"),
        CountryModel(name: "Moldova", code: "MD", flag: "🇲🇩"),
        CountryModel(name: "Monaco", code: "MC", flag: "🇲🇨"),
        CountryModel(name: "Mongolia", code: "MN", flag: "🇲🇳"),
        CountryModel(name: "Montenegro", code: "ME", flag: "🇲🇪"),
        CountryModel(name: "Morocco", code: "MA", flag: "🇲🇦"),
        CountryModel(name: "Mozambique", code: "MZ", flag: "🇲🇿"),
        CountryModel(name: "Myanmar (Burma)", code: "MM", flag: "🇲🇲"),
        CountryModel(name: "Namibia", code: "NA", flag: "🇳🇦"),
        CountryModel(name: "Nauru", code: "NR", flag: "🇳🇷"),
        CountryModel(name: "Nepal", code: "NP", flag: "🇳🇵"),
        CountryModel(name: "Netherlands", code: "NL", flag: "🇳🇱"),
        CountryModel(name: "New Zealand", code: "NZ", flag: "🇳🇿"),
        CountryModel(name: "Nicaragua", code: "NI", flag: "🇳🇮"),
        CountryModel(name: "Niger", code: "NE", flag: "🇳🇪"),
        CountryModel(name: "Nigeria", code: "NG", flag: "🇳🇬"),
        CountryModel(name: "North Korea", code: "KP", flag: "🇰🇵"),
        CountryModel(name: "North Macedonia", code: "MK", flag: "🇲🇰"),
        CountryModel(name: "Norway", code: "NO", flag: "🇳🇴"),
        CountryModel(name: "Oman", code: "OM", flag: "🇴🇲"),
        CountryModel(name: "Pakistan", code: "PK", flag: "🇵🇰"),
        CountryModel(name: "Palau", code: "PW", flag: "🇵🇼"),
        CountryModel(name: "Palestine State", code: "PS", flag: "🇵🇸"),
        CountryModel(name: "Panama", code: "PA", flag: "🇵🇦"),
        CountryModel(name: "Papua New Guinea", code: "PG", flag: "🇵🇬"),
        CountryModel(name: "Paraguay", code: "PY", flag: "🇵🇾"),
        CountryModel(name: "Peru", code: "PE", flag: "🇵🇪"),
        CountryModel(name: "Philippines", code: "PH", flag: "🇵🇭"),
        CountryModel(name: "Poland", code: "PL", flag: "🇵🇱"),
        CountryModel(name: "Portugal", code: "PT", flag: "🇵🇹"),
        CountryModel(name: "Qatar", code: "QA", flag: "🇶🇦"),
        CountryModel(name: "Romania", code: "RO", flag: "🇷🇴"),
        CountryModel(name: "Russia", code: "RU", flag: "🇷🇺"),
        CountryModel(name: "Rwanda", code: "RW", flag: "🇷🇼"),
        CountryModel(name: "Saint Kitts and Nevis", code: "KN", flag: "🇰🇳"),
        CountryModel(name: "Saint Lucia", code: "LC", flag: "🇱🇨"),
        CountryModel(name: "Saint Vincent and the Grenadines", code: "VC", flag: "🇻🇨"),
        CountryModel(name: "Samoa", code: "WS", flag: "🇼🇸"),
        CountryModel(name: "San Marino", code: "SM", flag: "🇸🇲"),
        CountryModel(name: "Sao Tome and Principe", code: "ST", flag: "🇸🇹"),
        CountryModel(name: "Saudi Arabia", code: "SA", flag: "🇸🇦"),
        CountryModel(name: "Senegal", code: "SN", flag: "🇸🇳"),
        CountryModel(name: "Serbia", code: "RS", flag: "🇷🇸"),
        CountryModel(name: "Seychelles", code: "SC", flag: "🇸🇨"),
        CountryModel(name: "Sierra Leone", code: "SL", flag: "🇸🇱"),
        CountryModel(name: "Singapore", code: "SG", flag: "🇸🇬"),
        CountryModel(name: "Slovakia", code: "SK", flag: "🇸🇰"),
        CountryModel(name: "Slovenia", code: "SI", flag: "🇸🇮"),
        CountryModel(name: "Solomon Islands", code: "SB", flag: "🇸🇧"),
        CountryModel(name: "Somalia", code: "SO", flag: "🇸🇴"),
        CountryModel(name: "South Africa", code: "ZA", flag: "🇿🇦"),
        CountryModel(name: "South Korea", code: "KR", flag: "🇰🇷"),
        CountryModel(name: "South Sudan", code: "SS", flag: "🇸🇸"),
        CountryModel(name: "Spain", code: "ES", flag: "🇪🇸"),
        CountryModel(name: "Sri Lanka", code: "LK", flag: "🇱🇰"),
        CountryModel(name: "Sudan", code: "SD", flag: "🇸🇩"),
        CountryModel(name: "Suriname", code: "SR", flag: "🇸🇷"),
        CountryModel(name: "Sweden", code: "SE", flag: "🇸🇪"),
        CountryModel(name: "Switzerland", code: "CH", flag: "🇨🇭"),
        CountryModel(name: "Syria", code: "SY", flag: "🇸🇾"),
        CountryModel(name: "Tajikistan", code: "TJ", flag: "🇹🇯"),
        CountryModel(name: "Tanzania", code: "TZ", flag: "🇹🇿"),
        CountryModel(name: "Thailand", code: "TH", flag: "🇹🇭"),
        CountryModel(name: "Timor-Leste", code: "TL", flag: "🇹🇱"),
        CountryModel(name: "Togo", code: "TG", flag: "🇹🇬"),
        CountryModel(name: "Tonga", code: "TO", flag: "🇹🇴"),
        CountryModel(name: "Trinidad and Tobago", code: "TT", flag: "🇹🇹"),
        CountryModel(name: "Tunisia", code: "TN", flag: "🇹🇳"),
        CountryModel(name: "Turkey", code: "TR", flag: "🇹🇷"),
        CountryModel(name: "Turkmenistan", code: "TM", flag: "🇹🇲"),
        CountryModel(name: "Tuvalu", code: "TV", flag: "🇹🇻"),
        CountryModel(name: "Uganda", code: "UG", flag: "🇺🇬"),
        CountryModel(name: "Ukraine", code: "UA", flag: "🇺🇦"),
        CountryModel(name: "United Arab Emirates", code: "AE", flag: "🇦🇪"),
        CountryModel(name: "United Kingdom", code: "GB", flag: "🇬🇧"),
        CountryModel(name: "United States of America", code: "US", flag: "🇺🇸"),
        CountryModel(name: "Uruguay", code: "UY", flag: "🇺🇾"),
        CountryModel(name: "Uzbekistan", code: "UZ", flag: "🇺🇿"),
        CountryModel(name: "Vanuatu", code: "VU", flag: "🇻🇺"),
        CountryModel(name: "Venezuela", code: "VE", flag: "🇻🇪"),
        CountryModel(name: "Vietnam", code: "VN", flag: "🇻🇳"),
        CountryModel(name: "Yemen", code: "YE", flag: "🇾🇪"),
        CountryModel(name: "Zambia", code: "ZM", flag: "🇿🇲"),
        CountryModel(name: "Zimbabwe", code: "ZW", flag: "🇿🇼")
    ]
}
